### ISSUE TITLE
Issue with typescript 2.4.x and ts-node 2.x.x.

### ISSUE THREAD

**Issue by michaelferwer** [ThomRick/nest-typescript-starter#1]
Hello Thomas.

I've met an issue when i use our starter used by @nestjs/cli.
In the package.json, typescript can be updated by npm in minor version. So I have typescript 2.4.1 in my node-modules but ts-node 2.1.0 seems to not be working with typescript 2.4.x.

Could you please investigate this ?

**Comment by ThomRick** [comment]
Hey @michaelferwer !

Ok I'll check to publish a fix as soon as possible !

Thanks ;-)

**Comment by ThomRick** [comment]
Hey @michaelferwer !

The typescript template is fixed but it could be hard to manage the update.
Just copy / paste the template package.json dependencies and devDependencies then rm your node_modules and run install.

Let me know if it's ok to close the issue ;-)
